### ISSUE TITLE
我按照教程可以成功翻墙了，但是为什么还是访问不了Quora和一些网站？

### ISSUE THREAD

**Issue by szupzj18** [zhaoweih/Shadowsocks-Tutorial#1]
我购买的云服务器地址是日本

**Comment by BlankAix** [comment]
Quora的速度是很慢的，我也不知道为什么。
至于你说的其他网站，如果开全局代理还是进不去的话，就是网络问题。如果可以的话，就说明PAC文档里面没有添加这个网址进去，它默认不翻墙。

**Comment by szupzj18** [comment]
我尝试了一下，全局模式下确实能访问了，应该是pac文档的问题。非常感谢！
