### ISSUE TITLE
mac mail裡面的GMAIL连接失败

### ISSUE THREAD

**Issue by zhiyzuo** [zhaoweih/Shadowsocks-Tutorial#10]
首先感谢您的教程！简单操作！

我在macOS 10.14.4 和iOS12上都能成功使用这种方法，但是在macOS的mail.app上卻一直连接不上gmail，只能在gmail的网页端登陆。我在ios上链接gmail没有任何问题。请问这个可以怎么解决吗？十分感谢！

**Comment by zhaoweih** [comment]
你好，若浏览器外的其他软件也要使用代理的话，设置代理服务器为 127.0.0.1，端口为1080(默认为1080)，类型为socks5代理

**Comment by zhiyzuo** [comment]
你好，谢谢你的回复。是如下图设置吗？
![image](https://user-images.githubusercontent.com/7501149/59047073-c5c52300-88b5-11e9-8c42-46d8d7ada59d.png)

可是这样一来不只我的gmail，就连icloud的mailbox也连接不上了。其他的两个exchange都一直没问题。
