### ISSUE TITLE
连不上

### ISSUE THREAD

**Issue by todoitnow** [zhaoweih/Shadowsocks-Tutorial#13]
最近用xshell老是连不上。已经换了太多的服务器了！ @zhaoweih

**Comment by zhaoweih** [comment]
Ehhh...最近是敏感时期，你可以试一下其他需要paypal的服务商，例如[digitalocean](https://m.do.co/c/6a45e437ae9f)、[hosttus](https://hostus.us/)、[vpsserver](https://www.vpsserver.com/)。后面两的成功率很高，基本我开没有被封的，但是后面两不能随便销毁主机换ip的，且用珍惜吧。

或者试一下便宜的机场服务（如果不需要很稳定的话，机场服务线路多，而且快）：https://ssmgr.gyteng.com/user/index

😀

**Comment by todoitnow** [comment]
感谢推荐，我去试试！

**Comment by lfwin** [comment]
同，vultr大多数服务器试了，根本ping不通，真的，不是不爱国，tmd的为了科研查资料，浪费时间

**Comment by zhaoweih** [comment]
> 同，vultr大多数服务器试了，根本ping不通，真的，不是不爱国，tmd的为了科研查资料，浪费时间

可以尝试下欧洲那边的线路，虽然慢了点，但是还是可以用的
