### ISSUE TITLE
求助，在使用vutlr时遇到这个问题

### ISSUE THREAD

**Issue by heguohui2018** [zhaoweih/Shadowsocks-Tutorial#17]
运行 which yum
which: no yum in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/opt/bin)
在服务器上并没有这个包管理工具，我搜索了很长时间，问题一直没有解决，
mycloud bin # yum install python
-bash: yum: command not found
使用的是：centos6

**Comment by zhaoweih** [comment]
可以参考这篇文章https://newsn.net/say/centos-yum.html
