### ISSUE TITLE
mac上无法连接

### ISSUE THREAD

**Issue by nigel193** [zhaoweih/Shadowsocks-Tutorial#18]
新手小白第一次操作,很多不懂,请求指教~
1.root@xxxx这样是成功了吗?
![Snip20190816_1](https://user-images.githubusercontent.com/40156041/63150732-374dea00-c03a-11e9-937e-f0b7009e97bf.png)
2.如果上面成功了是不是再设置ShadowsocksX-NG就可以了
3.ShadowsocksX-NG如何设置,网站只提供了ip和密码,端口号和加密方式如何设置
![Snip20190816_2](https://user-images.githubusercontent.com/40156041/63150982-decb1c80-c03a-11e9-903f-eab2d141b875.png)
![Snip20190816_3](https://user-images.githubusercontent.com/40156041/63150986-e38fd080-c03a-11e9-9b9c-16accc4ed5b5.png)
打扰了,谢谢

**Comment by zhaoweih** [comment]
1.这个只是登入了服务器，还没在服务器里面配置shadowsocks，配置流程请看教程
2.完成第一步配置完成shadowsocks后，用配置的端口号、密码和加密方式填入MAC客户端

**Comment by nigel193** [comment]
非常感谢你的回复.网上大多是window的ss搭建,给后面也有此困惑的人提示一下,使用"Mac Vultr SSR"做关键字搜索就可以了
