### ISSUE TITLE
pac模式无法翻墙

### ISSUE THREAD

**Issue by J-zin** [zhaoweih/Shadowsocks-Tutorial#19]
安装流程做了一遍。。发现还是无法翻墙
用的是pac模型。。为什么？？

**Comment by zhaoweih** [comment]
1.先确定服务器是否被墙了
2.再看看服务器配置信息和客户端填的是否一样

**Comment by J-zin** [comment]
@zhaoweih 
能ping通ip
信息也一样。。。
哭liao

**Comment by zhaoweih** [comment]
你看看设置的端口是否可以连通

**Comment by Changzw** [comment]
这个 脚本好像有问题，原作的的 git 仓库已经被河蟹了。。。

**Comment by Changzw** [comment]
试了 很多遍 最 生成 vmess URL 配置 也不行。。。。 醉了醉了
大家有没有 新的 v2ray 服务器搭建脚本 share 下？
