### ISSUE TITLE
ubuntu使用vpn账号翻墙？

### ISSUE THREAD

**Issue by henbucuoshanghai** [zhaoweih/Shadowsocks-Tutorial#20]
以前是设置好manual- socks host

然后命令 sslocal -s 账号-p 8097 -k "密码" -b 127.0.0.1 -l 1080
就可以翻墙

操作很简单
请问这是怎样操作的呢？忘了。。。。
求教

**Comment by zhaoweih** [comment]
你好，我还没有试过在ubuntu上作为客户端安装shadowsocks。
你可以参考这个文章：[Ubuntu安装和使用shadowsocks](https://zhoujianshi.github.io/articles/2018/Ubuntu%E5%AE%89%E8%A3%85%E5%92%8C%E4%BD%BF%E7%94%A8shadowsocks/index.html)

**Comment by henbucuoshanghai** [comment]
你好，试过很多种，失败了。。

**Comment by Emir-Liu** [comment]
我是使用ubuntu的如果需要可以问我，
这是我写的：https://emir-liu.github.io/2019/09/17/Ubuntu上shadowsocks配置/
然后我有一个仓库有关于ubuntu下一键配置客户端和服务器

**Comment by henbucuoshanghai** [comment]
你好多谢回复按照你的三个流程，就可以吗？我以前配置好json，上不去。。

**Comment by Emir-Liu** [comment]
恩。如果有问题，下面有检查问题的方法。我现在是直接通过ssh翻墙了

**Comment by Emir-Liu** [comment]
应该没问题，主要就是看服务器端和客户端有没有正常运行，运行之后，还需要代理服务器代理。。代理的部分我没写，我现在直接通过ssh翻墙的

**Comment by henbucuoshanghai** [comment]
那请问vpn账号呢？一般哪里买？多少钱？。。

**Comment by Emir-Liu** [comment]
vultr按小时计费，不用的时候可以把服务器关掉
