### ISSUE TITLE
关于ipv6

### ISSUE THREAD

**Issue by Looveteran** [zhaoweih/Shadowsocks-Tutorial#21]
ipv6根据你的教程，不能成功，请问ipv6怎么连接？

**Comment by zhaoweih** [comment]
你好，IPV6我还没有条件测试过，所以只能给你查询了相关文章：[搭建ipv6-VPN-让ipv4上ipv6-下载速度提升到100M](https://www.polarxiong.com/archives/%E6%90%AD%E5%BB%BAipv6-VPN-%E8%AE%A9ipv4%E4%B8%8Aipv6-%E4%B8%8B%E8%BD%BD%E9%80%9F%E5%BA%A6%E6%8F%90%E5%8D%87%E5%88%B0100M.html)
如果你解决了也可以留言解决方案，帮助跟你遇到同样问题的人
