### ISSUE TITLE
连接有问题

### ISSUE THREAD

**Issue by llaiyu** [zhaoweih/Shadowsocks-Tutorial#23]
手机上可以翻墙，但是电脑上一直ping不通

**Comment by zhaoweih** [comment]
你手机跟电脑是同一个网络吗

**Comment by JasonOscar** [comment]
不晓得，我最近还没开始用，只是先存的
----- 原始邮件 -----
发件人：Zhao Weihao <notifications@github.com>
收件人：zhaoweih/Shadowsocks-Tutorial <Shadowsocks-Tutorial@noreply.github.com>
抄送人：Subscribed <subscribed@noreply.github.com>
主题：Re:_[zhaoweih/Shadowsocks-Tutorial]_连接有问题_(#23)
日期：2019年09月20日 22点30分

你手机跟电脑是同一个网络吗



&mdash;

**Comment by zhaoweih** [comment]
ping不通不代表连不上的，如果你手机可以，确保你手机和电脑是同一个网络，用电脑客户端试试吧
