### ISSUE TITLE
服务器能ping通，一开始能成功谷歌，一分钟后就再也上不了了

### ISSUE THREAD

**Issue by jytime** [zhaoweih/Shadowsocks-Tutorial#24]
请问这种问题有遇到过吗~
即使在上不了的情况下，那个服务器还是可以ping通

**Comment by JasonOscar** [comment]
不好意思，我也是转载的，你可以去原链接看看。我最近也在研究。有结果了大家交流。
----- 原始邮件 -----
发件人：Jianyuan Wang <notifications@github.com>
收件人：zhaoweih/Shadowsocks-Tutorial <Shadowsocks-Tutorial@noreply.github.com>
抄送人：Subscribed <subscribed@noreply.github.com>
主题：[zhaoweih/Shadowsocks-Tutorial]_服务器能ping通，一开始能成功谷歌，一分钟后就再也上不了了_(#24)
日期：2019年09月21日 02点17分

请问这种问题有遇到过吗~


即使在上不了的情况下，那个服务器还是可以ping通



&mdash;
