### ISSUE TITLE
连接问题

### ISSUE THREAD

**Issue by tianhub** [zhaoweih/Shadowsocks-Tutorial#25]
刚搭建可以翻,过2天翻不了了,ping下地址是能通的,大佬你知道是啥情况吗,,,,,

**Comment by zhaoweih** [comment]
你能用ssh登录服务器吗，能的话应该是端口被封了，换个端口试试。
或者试一下[v2ray](https://github.com/zhaoweih/Shadowsocks-Tutorial/blob/master/super_easy_v2ray_tutorial.md)

**Comment by tianhub** [comment]
谢谢大佬 我尝试一下




------------------ 原始邮件 ------------------
发件人: "Zhao Weihao"<notifications@github.com>; 
发送时间: 2019年9月25日(星期三) 晚上10:59
收件人: "zhaoweih/Shadowsocks-Tutorial"<Shadowsocks-Tutorial@noreply.github.com>; 
抄送: "tian"<1149375181@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [zhaoweih/Shadowsocks-Tutorial] 连接问题 (#25)




你能用ssh登录服务器吗，能的话应该是端口被封了，换个端口试试。
 或者试一下v2ray
