### ISSUE TITLE
wget failed

### ISSUE THREAD

**Issue by RedemptionC** [zhaoweih/Shadowsocks-Tutorial#3]
wget --no-check-certificate -O shadowsocks-all.sh https://raw.githubusercontent.com/teddysun/shadowsocks_install/master/shadowsocks-all.sh
--2019-01-08 11:10:51--  https://raw.githubusercontent.com/teddysun/shadowsocks_install/master/shadowsocks-all.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.228.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.228.133|:443... failed: Network is unreachable.

**Comment by zhaoweih** [comment]
网络无法连接，请提供更详细的错误信息，或者尝试更换服务器
