### ISSUE TITLE
[ERROE] Failed to install python and Docker

### ISSUE THREAD

**Issue by Zado-Tan** [zhaoweih/Shadowsocks-Tutorial#38]
Xshell 配置好密码后，安装pyhton 失败， 而且根据之前的issue 使用备用教程 安装docker也失败了

Press any key to start...or Press Ctrl+C to cancel
[Info] Checking the EPEL repository...
[Info] Checking the EPEL repository complete...
[Info] Starting to install package unzip
[Info] Starting to install package gzip
[Info] Starting to install package openssl
[Info] Starting to install package openssl-devel
[Info] Starting to install package gcc
[Info] Starting to install package python
[Error] Failed to install python
Please visit: https://teddysun.com/486.html and contact.
[root@vultrguest ~]# ^C
[root@vultrguest ~]# sudo bash -c "$(wget -qO- https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/server_manager/install_scripts/install_server.sh)"
> Verifying that Docker is installed .......... NOT INSTALLED
> Would you like to install Docker? This will run 'curl -sS https://get.docker.com/ | sh'. [Y/n] y
> Installing Docker ........................... Docker installation failed, please visit https://docs.docker.com/install for instructions.

Sorry! Something went wrong. If you can't figure this out, please copy and paste all this output into the Outline Manager screen, and send it to us, to see if we can help you.
[root@vultrguest ~]# ^C
[root@vultrguest ~]#

**Comment by RZYN2020** [comment]
我也一样，请问有解决方法了吗

**Comment by zhaoweih** [comment]
> 我也一样，请问有解决方法了吗

可以尝试使用Debian10x64系统，我前阵子也是用的Debian10x64没有问题

**Comment by zhaoweih** [comment]
由于以前文章的centos7不可选导致选择centos8导致的无法安装问题可以尝试使用Debian10x64系统安装

**Comment by zhaoweih** [comment]
#27 (comment)

**Comment by RZYN2020** [comment]
> 由于以前文章的centos7不可选导致选择centos8导致的无法安装问题可以尝试使用Debian10x64系统安装

问题已解决。谢谢！
