### ISSUE TITLE
SS 搭建还是遇到问题，求教

### ISSUE THREAD

**Issue by tikobest** [zhaoweih/Shadowsocks-Tutorial#39]
Sorry! Something went wrong. If you can't figure this out, please copy and paste all this output into the Outline Manager screen, and send it to us, to see if we can help you.

> Verifying that Docker is installed .......... NOT INSTALLED
> Would you like to install Docker? This will run 'curl -sS https://get.docker.com/ | sh'. [Y/n] y
> Installing Docker ........................... Docker installation failed, please visit https://docs.docker.com/install for instructions.

**Comment by zhaoweih** [comment]
你好，你是按着教程的步骤来的吗？请问你是什么版本的系统？

或者你尝试一下普通教程：https://github.com/zhaoweih/Shadowsocks-Tutorial/blob/master/README.md

**Comment by zhaoweih** [comment]
或者你自己安装一个docker，然后再执行命令
