### ISSUE TITLE
做完所有步骤 但是不成功

### ISSUE THREAD

**Issue by qiezi123456** [zhaoweih/Shadowsocks-Tutorial#41]
您好！我根据备用教程的所有步骤一个个做下来之后，成功拿到了ss的绿色代码 和 outline的access key，但是最后还是不能成功，想请教一下您是否知道我哪里有问题。十分感谢。

<img width="804" alt="Screen Shot 2021-01-01 at 2 56 34 PM" src="https://user-images.githubusercontent.com/19893730/103434867-3bd06e00-4c42-11eb-83f1-297e39b73535.png">
<img width="360" alt="Screen Shot 2021-01-01 at 2 56 25 PM" src="https://user-images.githubusercontent.com/19893730/103434869-3f63f500-4c42-11eb-8457-14773b7a20e3.png">

**Comment by zhaoweih** [comment]
这样我很难判断是什么问题，可以私发你的配置信息到我邮箱我帮你看看吗，或者你参考另外一篇文章试试：https://github.com/zhaoweih/Shadowsocks-Tutorial/blob/master/README.md
