### ISSUE TITLE
你好，请问如何解决无法访问谷歌学术的问题

### ISSUE THREAD

**Issue by FutureForMe** [zhaoweih/Shadowsocks-Tutorial#44]
你好，按照你的教程我已经成功安装并启动了shadowsocks，可以正常访问谷歌网站，在vultr服务器中也配置了ipv6，但是访问谷歌学术网址时无法进行，提示信息如下：
We're sorry...
... but your computer or network may be sending automated queries. To protect our users, we can't process your request right now.

See Google Help for more information.

**Comment by zhaoweih** [comment]
由于谷歌有自己的一套反代理爬虫的机制，所以很多 VPS 的 ip 会被谷歌检测到是代理，遇到这种情况可以用更换服务器即可，如果没有其他服务器可用，可以用[谷歌学术镜像](https://ac.scmor.com/)。

**Comment by zhaoweih** [comment]
都可以，比较方便的是在vultr下更换其他地方的服务器试试，可以参考一下这个文章：https://www.zhihu.com/question/21785670

**Comment by FutureForMe** [comment]
好的，十分感谢您的回答

**Comment by FutureForMe** [comment]
您好，我还有一个小问题想请教一下，就是在建立服务器的时候我看您建议选择Debian模式，请问一下这个Debian模式是什么意思啊？是机器的大小端模式吗？

**Comment by zhaoweih** [comment]
这不是，只是linux系统发行版的名称

FutureForMe <notifications@github.com> 于 2021年3月5日周五 上午9:59写道：
