### ISSUE TITLE
Ubuntu18.04

### ISSUE THREAD

**Issue by ShijieXue749** [zhaoweih/Shadowsocks-Tutorial#46]
您好，我按照您的教程步骤至服务器安装ss，获得IP、端口等信息
之后按照https://www.ywowl.com/os/linux/2017/05/513.html配置了ubuntu的客户端，但是启动后IP地址并没有改变，请问您能给我提供一些建议吗？谢谢您

**Comment by zhaoweih** [comment]
@ShijieXue749 不好意思，我这边还没有用过linux的客户端

**Comment by zhaoweih** [comment]
linux客户端的教程可以参考一下这个文章:https://shadowsockshelp.github.io/Shadowsocks/linux.html
