### ISSUE TITLE
昨天开始用不了vultr了 无论移动端还是pc端，只要一用SSR, 远程服务器的ip就再也ping不通

### ISSUE THREAD

**Issue by sixuerain** [zhaoweih/Shadowsocks-Tutorial#5]

**Comment by sixuerain** [comment]
只能重启远程服务器才能重新在PC ping通。
1/手机连ssr
2/PC ping 远程服务器  -- 不通了

**Comment by zhaoweih** [comment]
请问你的地区和运营商是什么

**Comment by skyoung** [comment]
我最近也无法访问了，可以ping通，但是shadowsocks就是不管用

**Comment by zhaoweih** [comment]
我最近有些服务器移动连接不了，电信没有问题，估计是移动的自建墙，如果无法访问可以更换服务器商或者更换服务器，例如更换到一些小众的服务器商

**Comment by a374064165** [comment]
怕是5美元套餐都被墙了，日本新加坡，美国欧洲- -没几个能用的。
