### ISSUE TITLE
服务器国内外能Ping通，按照教程建立好SSH账号，但就是翻不了墙。

### ISSUE THREAD

**Issue by Hooorace** [zhaoweih/Shadowsocks-Tutorial#52]
使用美国Debian服务器，服务器国内外检测服务器都能Ping通，按照教程建立好SSH账号。但就是翻不了墙。现在也不是很清楚什么原因。请问博主遇到过这种情况吗？

**Comment by zhaoweih** [comment]
你好，请问是确认按照流程走完了吗？建立好SSH账号是什么意思？ ***@***.***
，我给你测试下？

Horace ***@***.***> 于2022年1月9日周日 11:46写道：

**Comment by zhaoweih** [comment]
> 使用美国Debian服务器，服务器国内外检测服务器都能Ping通，按照教程建立好SSH账号。但就是翻不了墙。现在也不是很清楚什么原因。请问博主遇到过这种情况吗？

你好，请问是确认按照流程走完了吗？建立好SSH账号是什么意思？ 如果可以你可以把配置发我邮箱zhaoweihao.dev@gmail.com，我给你测试下？

**Comment by zhaoweih** [comment]
> 使用美国Debian服务器，服务器国内外检测服务器都能Ping通，按照教程建立好SSH账号。但就是翻不了墙。现在也不是很清楚什么原因。请问博主遇到过这种情况吗？

你好，经过测试一边流程是没有问题的，你可以尝试换一个服务器试试

**Comment by Hooorace** [comment]
后来换了服务器和脚本才行，不清楚是不是什么问题。

**Comment by Hooorace** [comment]
你好，我通过邮件将我遇到的问题发给你了，可以麻烦你帮忙看一下吗？

**Comment by zhaoweih** [comment]
我之前在公司用电脑你的配置ok（公司网络有跨境专线），但是今天用家里的网络测试连不上（不知道你的配置是否有更改），那就有可能是这个服务器ip被墙了，你可以更换一个服务器试一下
