### ISSUE TITLE
2022.5.3——按照这个方法配置了完整的shadowsocks，可是还是无法成功

### ISSUE THREAD

**Issue by Jazihars** [zhaoweih/Shadowsocks-Tutorial#54]
非常感谢作者提供的这个教程，很有帮助！不过我按照这个教程配置了完整的shadowsocks-libev，Vultr的VPS服务器选择的是德国法兰克福，可是还是无法成功科学上网。不知道现在是不是这个方法已经失效了？

**Comment by Jazihars** [comment]
如果这个方法失效了，请问作者是否可以适当更新？再次感谢您的教程！

**Comment by Jazihars** [comment]
在cmd中测试ping my_vps_ip能够成功，加密方法选择的是xchacha20-ietf-poly1305，端口随便写了一个数。客户端下载的是最新版本的windows shadowsocks客户端https://github.com/shadowsocks/shadowsocks-windows/releases/tag/4.4.1.0 。但是仍然无法科学上网。不知道是什么原因？

**Comment by weishaopenggege** [comment]
> 在cmd中测试ping my_vps_ip能够成功，加密方法选择的是xchacha20-ietf-poly1305，端口随便写了一个数。客户端下载的是最新版本的windows shadowsocks客户端https://github.com/shadowsocks/shadowsocks-windows/releases/tag/4.4.1.0 。但是仍然无法科学上网。不知道是什么原因？

好多年前参考这个成功搭建了, 后来服务器到期后就停了, 前段时间参考这个教程又搭建了一次, 发现不行了, 而且注册美版appId那个知乎的链接教程, 好像也不行了, 不知道有哪位大哥有最新的SSR搭建教程和美区appId的注册教程啊

**Comment by Jazihars** [comment]
> 好多年前参考这个成功搭建了, 后来服务器到期后就停了, 前段时间参考这个教程又搭建了一次, 发现不行了, 而且注册美版appId那个知乎的链接教程, 好像也不行了, 不知道有哪位大哥有最新的SSR搭建教程和美区appId的注册教程啊

可以参考[这个仓库](https://github.com/Alvin9999/new-pac)
