### ISSUE TITLE
kcptun安装成功，但是连不上网

### ISSUE THREAD

**Issue by Hooorace** [zhaoweih/Shadowsocks-Tutorial#55]
kcptun服务端都安装成功了，但是连不上网，不知道博主有没有遇到这样的问题。

服务器系统：Debian 10x64
kcp版本：windows amd64 20210922

**Comment by zhaoweih** [comment]
> kcptun服务端都安装成功了，但是连不上网，不知道博主有没有遇到这样的问题。
> 
> 服务器系统：Debian 10x64 kcp版本：windows amd64 20210922

可以确认下服务端配置跟客户端是否一致

**Comment by JackLoveCherry** [comment]
我也遇到了同样的问题

**Comment by JackLoveCherry** [comment]
![局部截取_20240921_002957](https://github.com/user-attachments/assets/05c2208b-9174-4f27-a898-9ed22ec1c0a0)
![局部截取_20240921_003032](https://github.com/user-attachments/assets/8f7f05db-759e-4a75-b8b9-b66d7a9be15d)
