### ISSUE TITLE
Mac系统按照步骤一步一步完成了，还是打不开google？

### ISSUE THREAD

**Issue by ffstnt** [zhaoweih/Shadowsocks-Tutorial#6]
前面所有步骤都没处岔子，不知道还是没法成功fanqiang

**Comment by ffstnt** [comment]
我自己傻逼了，在终端连接ssh root时，显示time out，应该是没连上。

**Comment by ffstnt** [comment]
然后又重新部署了一个server，换了一个新ip，还是连接不上。。。

**Comment by ffstnt** [comment]
换了一个老远的地方，应该是连接上了。但后面还是无法正常打开Google。。我想问，mac在完成ssh root后，不需要再安装ss了吗？我的步骤是ssh root连接成功后，安装shadowsocks app，更改服务器设置，设置PAC自动模式，然而还是打不开google。。

**Comment by ffstnt** [comment]
另外在服务器设置时不知道端口是多少，也不知道密码方式是啥。因为vultr里面只有ip和密码。。求大神解惑。。

**Comment by zhaoweih** [comment]
服务器设置的端口和密码方式跟你的ip和密码没有关系的，你可以按照默认的，不过要记住，因为填进mac端的时候需要用到

**Comment by ffstnt** [comment]
谢谢博主回复啊！我试了好几个shadowsocks install SSR，终端安装的时候都提示“no support os”...安装ssr失败。。

**Comment by ffstnt** [comment]
感激呀！倒腾了一晚上终于搞定了～我的google又回来了～

**Comment by nigel193** [comment]
> 感激呀！倒腾了一晚上终于搞定了～我的google又回来了～

遇到和你一样的问题,请问最终是怎么处理的.端口和加密方式如何选择?
![Snip20190816_3](https://user-images.githubusercontent.com/40156041/63154608-949a6900-c043-11e9-9c97-2fa0156289cf.png)
