### ISSUE TITLE
ssr-bbr-vpn 

### ISSUE THREAD

**Issue by mazhijia** [zhaoweih/Shadowsocks-Tutorial#60]
这个项目最后输入/etc/init.d/shadowsocks start启动SSR时，报错:/usr/bin/env: 'python': no such file or directory  starting shadowsockes failed

**Comment by zhaoweih** [comment]
你好👋，你说的这个命令在我文章没有出现，如果你按照我文章的操作 安装的应该是shadowsocks-libev

具体libev的命令可以参考下面：
https://github.com/zhaoweih/Shadowsocks-Tutorial#shadowsocks-libev-%E7%89%88
