### ISSUE TITLE
【跳过公司内网访问B站】

### ISSUE THREAD

**Issue by zhang2458941525** [zhaoweih/Shadowsocks-Tutorial#61]
自己买了华为云服务器，linux系统，代理服务器部署了shadowsock，打开了华为云限制的端口，同时关闭云服务器的防火墙，在本地电脑下载shadowsock，添加配置信息后，还是无法打开B站，请问是哪里有问题吗

**Comment by zhaoweih** [comment]
这个用途我还没试过😹，你可以先看看你本地到服务器端口是否是通的

不做车手做豆腐 ***@***.***>于2024年4月18日 周四下午5:03写道：
