### ISSUE TITLE
IOS上连接后打不开Google

### ISSUE THREAD

**Issue by edenwang2024** [zhaoweih/Shadowsocks-Tutorial#62]
![3191715822311_ pic](https://github.com/zhaoweih/Shadowsocks-Tutorial/assets/169959088/1227ff84-8050-4ebe-849b-45327fcd4540)
![3201715822312_ pic](https://github.com/zhaoweih/Shadowsocks-Tutorial/assets/169959088/ba3ed425-ef1f-46c7-ae9b-838d941b4280)

**Comment by zhaoweih** [comment]
可以先看下端口是否通的，不通的话大概率是被墙了，可以销毁了重新开个试试

**Comment by edenwang2024** [comment]
首先谢谢楼主的回答！
![截屏2024-05-18 下午12 03 12](https://github.com/zhaoweih/Shadowsocks-Tutorial/assets/169959088/3f0812c1-9953-4250-a617-df0a6b705d54)
看起来似乎是通的，mac端可以正常用，但IOS端不行

**Comment by zhaoweih** [comment]
> 首先谢谢楼主的回答！ ![截屏2024-05-18 下午12 03 12](https://private-user-images.githubusercontent.com/169959088/331764076-3f0812c1-9953-4250-a617-df0a6b705d54.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMTc2MzEsIm5iZiI6MTcxNjIxNzMzMSwicGF0aCI6Ii8xNjk5NTkwODgvMzMxNzY0MDc2LTNmMDgxMmMxLTk5NTMtNDI1MC1hNjE3LWRmMGE2YjcwNWQ1NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMFQxNTAyMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMWQwMzBmZGRjMGZhYjcwMTFkODRiNGNmNDdjYzkxZWVkNjk0ZGE3MjhhYjgyNDE1NDViMTEyZWQ3MzEzNzA5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uzqOgVLD88JWQU7zwQzg6rshjfGkV-Tw1yuxyMSuKXk) 看起来似乎是通的，mac端可以正常用，但IOS端不行

你的截图是在服务器上ping服务器，你需要在你本地电脑ping。如果你在mac端可以正常使用的话代表你的服务器端配置其实是正常的，你可以检查下手机端配置是否填错了和确认你手机和电脑是否在同一个网络环境。

**Comment by zhaoweih** [comment]
因为有可能网络运营商不一样表现也不一样的

**Comment by edenwang2024** [comment]
多谢楼主！把加密方式换成"chacha..."就可以了！因为ios客户端里没有“xchacha..."
