### ISSUE TITLE
请问怎么在MAC上给centos 9 加速

### ISSUE THREAD

**Issue by majikjiong** [zhaoweih/Shadowsocks-Tutorial#65]
感谢up的教程让我成功搭建了server。我想给server加速但是不知道怎么在MAC上加速（不装其他系统的情况下）。求指教！谢谢！

**Comment by zhaoweih** [comment]
这个只是代理 无法给虚拟机加速，如果需要给需要给虚拟机加速可以试一下用shadowrocket

**Comment by majikjiong** [comment]
你好，
请问Shadowrocket显示time out怎么办😭昨天还能用，今天用不了了。

**Comment by zhaoweih** [comment]
看起来一般是连接服务器超时了，可以检查下服务器是否可以正常连接

**Comment by majikjiong** [comment]
怎么检查呀？Vultr上显示running，我用ping +ID ye m也没有time out。

**Comment by zhaoweih** [comment]
https://blog.csdn.net/weixin_41622043/article/details/92641015

可以参考这篇文章测试端口是否是通的
